include::../header.adoc[]

== Moving to the BeagleBone AI

So far all our examples have focussed on the BeagleBone Black and Pocket Beagle.
These are both based on the am335x chip.  The new kid on the black in the BeagleBone AI
which is based on the am5729. The new chip brings with it new capabilities one of
which is four PRUs.  This chapter details what changes when moving from two to
four PRUs.

The following are resources used in this chapter.

* TODO - check these

.Resources
* http://www.ti.com/lit/ug/spruhv7b/spruhv7b.pdf[PRU Optimizing C/C++ Compiler, v2.2, User's Guide]
* http://www.ti.com/lit/ug/spruhv6b/spruhv6b.pdf[PRU Assembly Language Tools User's Guide]
* http://www.ti.com/lit/ug/spruij2/spruij2.pdf[PRU Assembly Instruction User Guide]

=== Moving from two to four PRUs
==== Problem
You have code that works on the am335x PRUs and you want to move it to the 
am5729 on the AI.

==== Solution
Things to consider when moving to the AI are:

* Which pins are you going to use
* Which PRU are you going to run on

Knowing which pins to use impacts the PRU you'll use.

==== Discission
The various System Reference Manuals (SRM's) list which pins go to the PRUs.
Here the tables are combined into one to make it easier to see what goes where.

[[aimapping_bits]]
.Mapping bit positions to pin names
[width="50%", cols="1,1,3, 3, 3, 3"]
|===
|PRU|Bit|Black pin|AI PRU1 pin|AI PRU2 pin|Pocket pin

|0  |0  |P9_31    |  TODO     |P8_44      |P1.36     
|0  |1  |P9_29    |           |P8_41      |P1.33     
|0  |2  |P9_30    |           |P8_42      |P2.32     
|0  |3  |P9_28    |P8_12      |P8_39      |P2.30     
|0  |4  |P9_92    |P8_11      |P8_40      |P1.31     
|0  |5  |P9_27    |P9_15      |P8_37      |P2.34     
|0  |6  |P9_91    |           |P8_38      |P2.28     
|0  |7  |P9_25    |           |P8_36      |P1.29     
|0  |14 |P8_12(out) P8_16(in)    |           | TODO      |P2.24     
|0  |15 |P8_11(out) P8_15(in)    |           |           |P2.33     
|0  |16 |         |P9_41(in) P9_26(in)      |           |     
|---|---|---------|-----------|-----------|-----
|1  |0  |P8_45    |           |           |          
|1  |1  |P8_46    |P9_20      |           |          
|1  |2  |P8_43    |P9_19      |           |          
|1  |3  |P8_44    |P9_41      |           |          
|1  |4  |P8_41    |           |           |          
|1  |5  |P8_42    |P8_18      |           |          
|1  |6  |P8_39    |P8_19      |           |          
|1  |7  |P8_40    |P8_13      |           |          
|1  |8  |P8_27    |           |           |P2.35     
|1  |9  |P8_29    |P8_14      |           |P2.01     
|1  |10 |P8_28    |P9_42      |           |P1.35     
|1  |11 |P8_30    |P9_27      |           |P1.04     
|1  |12 |P8_21    |           |           |          
|1  |13 |P8_20    |           |           |          
|1  |14 |         |P9_14      |           |P1.32     
|1  |15 |         |P9_16      |           |P1.30     
|1  |16 |P9_26(in)         |P8_15      |           |     
|1  |17 |         |P8_26      |           |     
|1  |18 |         |P8_16      |           |     
|===

=== Seeing how pins are configured
==== Problem
You want to know how the pins are currently configured.

==== Solution
The `show-pins.pl` command does what you want, but you have to set it up first.

[source] 
[subs=+quotes]
----
bone$ *cd ~/bin*
bone$ *ln -s /opt/scripts/device/bone/show-pins.pl .*
----

This creates a symbolic link to the `show-pins.pl` command that is rather hidden
away.  The link is put in the `bin` directory which is in the default command
`$PATH`.  Now you can run `show-pins.pl` from anywhere.

[source] 
[subs=+quotes]
----
bone$ *show-pins.pl*
P9.19a                    16   R6 7 fast rx  up  i2c4_scl
P9.20a                    17   T9 7 fast rx  up  i2c4_sda
P8.35b                    57  AD9 e fast    down gpio3_0
P8.33b                    58  AF9 e fast    down gpio3_1
...
----
Here you see `P9.19a` and `P9.20a` are configured for i2c with pull up resistors.
The `P8` pins are configured as gpio with pull down resistors. They are 
both on gpio port 3.  `P8.35b` is bit 0 while `P8.33b` is bit 1. You can find
which direction they are set by using `gpioinfo` and the chip number.  
Unfortunately you subtract one from the port number to get the chip number.
So `P8.35b` is on chip number 2.

[source] 
[subs=+quotes]
----
bone$ *gpioinfo 2*
	line   0:      unnamed       unused   *input*  active-high 
	line   1:      unnamed       unused   *input*  active-high 
	line   2:      unnamed       unused   input  active-high 
	line   3:      unnamed       unused   input  active-high 
	line   4:      unnamed       unused   input  active-high 
...
----
Here we see both (lines 0 and 1) are set to input.

Adding `-v` gives more details.
[source] 
[subs=+quotes]
----
bone$ *show-pins.pl -v*
...
sysboot 14                14   H2 f fast    down sysboot14
sysboot 15                15   H3 f fast    down sysboot15
P9.19a                    16   R6 7 fast rx  up  i2c4_scl
P9.20a                    17   T9 7 fast rx  up  i2c4_sda
                          18   T6 f fast    down Driver off
                          19   T7 f fast    down Driver off
bluetooth in              20   P6 8 fast rx      uart6_rxd        mmc@480d1000 (wifibt_extra_pins_default)
bluetooth out             21   R9 8 fast rx      uart6_txd        mmc@480d1000 (wifibt_extra_pins_default)
...
----

The best way to use `show-pins.pl` is with `grep`.  To see all the pru pins try:
[source] 
[subs=+quotes]
----
bone$ *show-pins.pl  | grep -i pru | sort*
P8.13                    100   D3 c fast rx      pr1_pru1_gpi7
P8.15b                   109   A3 d fast    down pr1_pru1_gpo16
P8.16                    111   B4 d fast    down pr1_pru1_gpo18
P8.18                     98   F5 c fast rx      pr1_pru1_gpi5
P8.19                     99   E6 c fast rx      pr1_pru1_gpi6
P8.26                    110   B3 d fast    down pr1_pru1_gpo17
P9.16                    108   C5 d fast    down pr1_pru1_gpo15
P9.19b                    95   F4 c fast rx  up  pr1_pru1_gpi2
P9.20b                    94   D2 c fast rx  up  pr1_pru1_gpi1
----

Here we have nine pins configured for the PRU registers `R30` and `R31`.
Five are input pins and four are out.

=== Configuring pins on the AI via device trees
==== Problem
I want to configure another pin for the PRU, but I get an error.
[source] 
[subs=+quotes]
----
bone$ *config-pin P8.12 pruout*
ERROR: open() for /sys/devices/platform/ocp/ocp:P8_12_pinmux/state failed, No such file or directory
----

==== Solution
The pins on the AI must be configure at boot time and therefor cannot be
configured with `config-pin`.  Instead you must edit the device tree.

==== Discission
Suppose you want to make `P8.12` a PRU output pin. First go to the
https://github.com/beagleboard/beaglebone-ai/wiki/System-Reference-Manual#p8.10-p8.13[am5729 System Reference Manual]
and look up `P8.12`.  
[TIP]
====
The https://docs.google.com/spreadsheets/d/1dFSBVem86vAUD7MLXvqdS-N0Efi8_g_O1iTqzql8DAo/edit#gid=0[BeagleBone AI PRU pins]
table may be easier to use.
====

We see that when `P8.12` is set to `MODE13` it will be a PRU _out_ pin.  
`MODE12` makes it a PRU _in_ pin.  It appears at bit 3 on PRU1_0.

Next, find which kernel you are running.
[source] 
[subs=+quotes]
----
bone$ *uname -a*
Linux ai *4.14*.108-ti-r131 #1buster SMP PREEMPT Tue Mar 24 19:18:36 UTC 2020 armv7l GNU/Linux
----
I'm running the 4.14 version. Now look in `/opt/source` for your kernel.

[source] 
[subs=+quotes]
----
bone$ *cd /opt/source/*
bone$ *ls*
adafruit-beaglebone-io-python  *dtb-4.14-ti*  librobotcontrol  py-uio           u-boot_v2019.07-rc4
BBIOConfig                     dtb-4.19-ti  list.txt         rcpy
bb.org-overlays                dtb-5.4-ti   pyctrl           u-boot_v2019.04
bone$ *cd dtb-4.14-ti/src/arm/*
bone$ *ls am5729**
am5729-beagleboneai.dts  am5729-beagleboneai-roboticscape.dts
----
`am5729-beagleboneai.dts` is the file we need to edit.  Search for `P8.12`.
You'l see:
[subs=+quotes]
----
DRA7XX_CORE_IOPAD(0x3510, MUX_MODE14) // AH4: P8.11: vin1a_d7.off 
DRA7XX_CORE_IOPAD(0x350C, *MUX_MODE14*) // AG6: *P8.12*: vin1a_d6.off 
DRA7XX_CORE_IOPAD(0x3590, PIN_INPUT | MUX_MODE12) // D3: P8.13: vin2a_d10.off 
----

Change the `MUX_MODE14` to `MUX_MODE13` for output, or `MUX_MODE12` for input.

Compile and install.  The first time will take a while since it recompiles all
the dts files.

[subs=+quotes]
----
bone$ *make*
...
  DTC     src/arm/am335x-sl50.dtb
  *DTC     src/arm/am5729-beagleboneai.dtb*
  DTC     src/arm/am335x-nano.dtb
...
bone$ *sudo make install*
...
'src/arm/am5729-beagleboneai.dtb' -> '/boot/dtbs/4.14.108-ti-r131/am5729-beagleboneai.dtb'
...
bone$ *reboot*
...
bone$ *show-pins.pl -v | sort | grep -i pru*
*P8.12                     67  AG6 d fast    down pr1_pru0_gpo3*
P8.13                    100   D3 c fast rx      pr1_pru1_gpi7
P8.15b                   109   A3 d fast    down pr1_pru1_gpo16
P8.16                    111   B4 d fast    down pr1_pru1_gpo18
P8.18                     98   F5 c fast rx      pr1_pru1_gpi5
P8.19                     99   E6 c fast rx      pr1_pru1_gpi6
P8.26                    110   B3 d fast    down pr1_pru1_gpo17
P9.16                    108   C5 d fast    down pr1_pru1_gpo15
P9.19b                    95   F4 c fast rx  up  pr1_pru1_gpi2
P9.20b                    94   D2 c fast rx  up  pr1_pru1_gpi1
----
There it is.  `P8.12` is now a PRU output pin on PRU1_0, bit 3.
