include::../header.adoc[]

== Running a Program; Configuring Pins

There are a lot of details in compiling and running PRU code.
Fortunately those details are captured in a common `Makefile` that is
used througout this book.  This chapter shows how to use the `Makefile` to 
compile code and also start and stop the PRUs.

The following are resources used in this chapter.

.Resources
* http://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.1.5/ti_cgt_pru_2.1.5_armlinuxa8hf_busybox_installer.sh[PRU Code Generation Tools - Compiler]
* http://git.ti.com/pru-software-support-package[PRU Software Support Package]
* http://www.ti.com/lit/ug/spruhv7b/spruhv7b.pdf[PRU Optimizing C/C++ Compiler]
* http://www.ti.com/lit/ug/spruhv6b/spruhv6b.pdf[PRU Assembly Language Tools]
* http://www.ti.com/lit/pdf/spruhz6l[AM572x Technical Reference Manual] (AI)
* http://www.ti.com/lit/pdf/spruh73[AM335x Technical Reference Manual] (All others)

=== Getting Example Code
==== Problem
I want to get the files used in this book.

==== Solution
It's all on a GitHub repository.
[source]
[subs=+quotes]
----
bone$ *git clone https://github.com/MarkAYoder/PRUCookbook.git*
----

=== Compiling and Running
==== Problem
I want to compile and run an example.

==== Solution
Change to the directory of the code you want to run.
[source]
[subs=+quotes]
----
bone$ *cd PRUCookbook/docs/06io/code*
bone$ *ls*
gpio.pru0.c  Makefile  setup.sh
----

Source the setup file.
[source]
[subs=+quotes]
----
bone$ *source setup.sh*
TARGET=gpio.pru0
----

Now you are ready to compile and run.  This is automated for you in the Makefile
[source]
[subs=+quotes]
----
bone$ *make*
/var/lib/cloud9/common/Makefile:28: MODEL=TI_AM335x_BeagleBone_Black,TARGET=gpio.pru0,COMMON=/var/lib/cloud9/common
/var/lib/cloud9/common/Makefile:147: GEN_DIR=/tmp/cloud9-examples,CHIP=am335x,PROC=pru,PRUN=0,PRU_DIR=/sys/class/remoteproc/remoteproc1,EXE=.out
-    Stopping PRU 0
/bin/sh: 1: echo: echo: I/O error
Cannot stop 0
CC	gpio.pru0.c
"/var/lib/cloud9/common/prugpio.h", line 53: warning #1181-D: #warning directive: "Found am335x"
LD	/tmp/cloud9-examples/gpio.pru0.o
-	copying firmware file /tmp/cloud9-examples/gpio.pru0.out to /lib/firmware/am335x-pru0-fw
write_init_pins.sh
writing "out" to "/sys/class/gpio/gpio30/direction"
-    Starting PRU 0
MODEL   = TI_AM335x_BeagleBone_Black
PROC    = pru
PRUN    = 0
PRU_DIR = /sys/class/remoteproc/remoteproc1
rm /tmp/cloud9-examples/gpio.pru0.o
----
Congratulations, your are now running a PRU.  If you have an LED attached to
`P9_11` it should be blinking.

==== Discussion
The `setup.sh` file sets the `TARGET` to the file you want to compile.
Set it to the filename, without the `.c` extension (`gpio.pru0`).
The file extension `.pru0` specifies the number of the PRU you are using 
(either `1_0`, `1_1`, `2_0`, `2_1` on the AI or `0` or `1` on the others)

You can override the `TARGET` on the command line.

[subs=+quotes]
----
bone$ *cp gpio.pru0.c gpio.pru1.c*
bone$ *export TARGET=gpio.pru1*
----

Notice the `TARGET` doesn't have the `.c` on the end.

You can also specify them when running `make`.
[subs=+quotes]
----
bone$ *cp gpio.pru0.c gpio.pru1.c*
bone$ *make TARGET=gpio.pru1*
----

The setup file also contains instructions to figure out which Beagle you are running
and then configure the pins acordingly.

* TODO - Fix config-pin

.setup.sh
[source,linenums]
[subs=+quotes]
----
include::code/gpio_setup.sh[]
----

[cols="1,9"]
|===
|Line|Explanation

|2-5 |Set which PRU to use and which file to compile. 
|8   |Figure out which type of Beagle we have.
|10-22|Based on the type, set the `pins`.
|24-29|Configure (set the pin mux) for each of the pins.
|===


The `Makefile` stops the PRU, compiles the file and moves it where it will 
be loaded, and then restarts the PRU.

=== Stopping and Starting the PRU
==== Problem
I want to stop and start the PRU.

==== Solution
It's easy.
[source]
[subs=+quotes]
----
bone$ *make stop*
-    Stopping PRU 0
stop
bone$ *make start*
-    Starting PRU 0
start
----
See <<../04debug/debug.html#_dmesg_hw,dmesg -Hw>> to see how to tell if the PRU
is stopped.

This assumes `TARGET` is set to the PRU you are using.
If you want to control the other PRU use:
[source]
[subs=+quotes]
----
bone$ *cp gpio.pru0.c gpio.pru1.c*
bone$ *make TARGET=gpio.pru1*
bone$ *make TARGET=gpio.pru1 stop*
bone$ *make TARGET=gpio.pru1 start*
----


[[details_makefile]]
=== The Standard Makefile

* TODO - Make this into how to use the standard Makefile

==== Problem
There are all sorts of options that need to be set when compiling
a program.  How can I be sure to get them all right?

==== Solution
The surest way to make sure everything is right is to use our
standard `Makefile`.

==== Discussion
It's assumed you already know how Makefiles work.  If not, there are
many resources online that can bring you up to speed.
Here is the stardard `Makefile` used throughout this book.

.Standard Makefile
[source,makefile,linenums]
----
include::code/Makefile[]
----

Here's an highlevel overview of the Makefile
// ToDo:  The long lines in the Makefile make the line numbers be off.

.Makefile Overview
[cols="1,9"]
|===
|Line |Explanation

|6,7  |You need to define `TARGET` and `PRU` before running the Makefile.
This is done in a `setup.sh`. `TARGET` is the name of the c source file, without
the `.c`.  `PRUN` is the number of the PRU for which you are compiling.
In our case it's either 0 or 1.
|12,13|These tell where to find the PRU compiler and the support libraries.
These files are already installed on the standard Beagle images. 
If they aren't installed you can find them at 
http://software-dl.ti.com/codegen/esd/cgt_public_sw/PRU/2.1.5/ti_cgt_pru_2.1.5_armlinuxa8hf_busybox_installer.sh[PRU Code Generation Tools - Compiler] and
http://git.ti.com/pru-software-support-package[PRU Software Support Package].
|14  |This is where all the generated files are stored. `/tmp` is used since
these files aren't needed once the PRU is running. Running `make clean` removes
these files for the given PRUN.  If you look in the directory you'll find: +
//TODO Make this format like code.
`bone$ *ls /tmp/pru0-gen/* +
file.map  gpio1.asm  gpio1.lst  gpio1.obj  gpio1.out  gpio1.pp` +
`file.map` shows what addresses the symbols are mapped to and `.lst` 
is the assembly code output by the compiler.  It might be useful to see
what your code is being compiled to.
The `.out` file is the generated code.
|16   |This points to the file that tells the linker where in memory to
put things.  It will be covered in <<detail_linker>>.
|17,18|Tells where to find the PRU libraries and include files.
|20,21|This gives the ((stack)) and ((heap sizes)). 
`STACK_SIZE` is the size of section `.stack` and 
`HEAP_SIZE` is the size of the `.bss` section.
|23,27|Flags for the c compiler and the linker
|30-36|Here we map the PRU number to its physical address. This is needed later
when loading the PRU. These addresses are fixed, no matter which Beagle you
are using.
|38   |This computes the path to the given PRU. If you look in this directory
you will find `state` and `firmware` (among other things).  `state` tells you
if the PRU is running or not. +
`bone$ *cat state*` +
`running` +
`firmware` is the name of the file in
`/lib/firmware` to copy the `.out` file to that the PRU is to run.
|41   |Since this is the first rule, it's the one that's run what you enter
`make` without a target. So here we stop the PRU, install the code and then
start the PRU.
|43-45|This rule stops the current PRU by writing the command `stop` into the 
`state` file noted above.  It's a bit complicated since you have to have
root permission to write to the file.
|47-49|This does a simular thing for starting the PRU.
|51-54|The PRU code is installed by simply copying the generated `.out` file
to `/lib/firmware/am335x-pru__X__-fw` where __X__ is either 0 or 1 depending 
on the PRU being used.
|56-64|Rules for compiling and linking. Notice the `clpru` command has `-D=PRUN=$(PRUN)`.
This will define `PRUN` to equal the PRU number in the code being compiled. This
way the code can have conditional compilation based on which PRU it's being
compiled for.
|66-68|Rule for removing the generated files.
|===

//  TODO  The line numbers stop at 62

Fortunately you shouldn't have to modify the `Makefile`.

=== Compiling with clpru and lnkpru

==== Problem
You need details on the c compiler, linker and other tools for the PRU.

==== Solution
The PRU compiler and linker are already installed on the standard images.
They are called `clpru` and `lnkpru`.
[source]
[subs=+quotes]
----
bone$ *which clpru*
/usr/bin/clpru
----
Details on each can be found here:

* http://www.ti.com/lit/ug/spruhv7b/spruhv7b.pdf[PRU Optimizing C/C++ Compiler]
* http://www.ti.com/lit/ug/spruhv6b/spruhv6b.pdf[PRU Assembly Language Tools]

IN fact there are PRU versions of many of the standard code generation tools.

.code tools
[source]
[subs=+quotes]
----
bone$ *ls /usr/bin/*pru*
/usr/bin/abspru    /usr/bin/clistpru  /usr/bin/hexpru      /usr/bin/ofdpru
/usr/bin/acpiapru  /usr/bin/clpru     /usr/bin/ilkpru      /usr/bin/optpru
/usr/bin/arpru     /usr/bin/dempru    /usr/bin/libinfopru  /usr/bin/rc_test_encoders_pru
/usr/bin/asmpru    /usr/bin/dispru    /usr/bin/lnkpru      /usr/bin/strippru
/usr/bin/cgpru     /usr/bin/embedpru  /usr/bin/nmpru       /usr/bin/xrefpru
----
See the http://www.ti.com/lit/ug/spruhv6b/spruhv6b.pdf[PRU Assembly Language Tools] for more details.

[[detail_linker]]
=== The Linker Command File - am335x_pru.cmd

==== Problem
The linker needs to be told where in memory to place the code and variables.

==== Solution
`am335x_pru.cmd` is the standard linker command file that tells the linker
where to put what.

.am335x_pru.cmd
[source,linker,linenums]
----
include::code/am335x_pru.cmd[am335x_pru.cmd]
----

==== Discussion

The important things to notice in the file are given in the following table.

.AM335x_PRU.cmd important things
[cols="1,9"]
|===
|Line|Explanation

|16   |This is where the instructions are stored. See page 206 of the
https://www.ti.com/lit/ug/spruh73p/spruh73p.pdf[AM335x Technical Reference Manual]
|22   |This is where PRU 0's DMEM 0 is mapped.  It's also where PRU 1's
DMEM 1 is mapped.
|23   |The reverse to above.  PRU 0's DMEM 1 appears here and PRU 1's DMEM 0 
is here.
|26   |The shared memory for both PRU's appears here.
|72   |The `.text` section is where the code goes.  It's mapped to `IMEM`
|73   |The ((stack)) is then mapped to DMEM 0. Notice that DMEM 0 is one bank
of memory for PRU 0 and another for PRU1, so they both get their own stacks.
|74   |The `.bss` section is where the ((heap)) goes.
|===

Why is it important to understand this file?  If you are going to store things
in DMEM, you need to be sure to start at address 0x0200 since the ((stack)) and 
the ((heap)) are in the locations below 0x0200.

=== Loading Firmware

==== Problem
I have my PRU code all compiled and need to load it on the PRU.

==== Solution
It's a simple three step process.

. Stop the PRU
. Write the `.out` file to the right place in `/lib/firmware`
. Start the PRU.

This is all handled in the <<details_makefile>>.

==== Discussion

* TODO - update for AI

The PRUs appear in the Linux file space at
`/sys/devices/platform/ocp/4a32600*.pruss-soc-bus/4a300000.pruss`.

.Finding the PRUs
[source]
[subs=+quotes]
----
bone$ *cd /sys/devices/platform/ocp/4a326000.pruss-soc-bus/4a300000.pruss*
bone$ *ls*
4a320000.intc  4a338000.*pru1*  driver_override  of_node  subsystem
4a334000.*pru0*  driver         modalias         power    uevent
----

Here we see PRU 0 and PRU 1 in the path.  Let's follow PRU 0.

[source]
[subs=+quotes]
----
bone$ *cd 4a334000.pru0/remoteproc/remoteproc1*
bone$ *ls*
device  firmware  power  state  subsystem  uevent
----

Here we see the files that control PRU 0.  `firmware` tells where in `/lib/firmware`
to look for the code to run on the PRU.

[source]
[subs=+quotes]
----
bone$ *cat firmware*
am335x-pru0-fw
----

Therefore you copy your `.out` file to `/lib/firmware/am335x-pru0-fw`.

[[details_configure_servos]]
=== Configuring Pins for Controlling Servos
==== Problem
You want to ((configure)) the pins so the PRU _outputs_ are accessable.

==== Solution
It depends on which Beagle you are running on.  If you are on the Blue, everything is already configured for you.
If you are on the Black or Pocket you'll need to run the following script.

.servos_setup.sh
[source,linenums]
----
include::code/servos_setup.sh[servos_setup.sh]
----

==== Discussion
The first part of the code looks in `/proc/device-tree/model` to see which Beagle is running. Based on that it
assigns `pins` a list of pins to configure.  Then the last part of the script loops through each of the pins and configures it.


[[details_configure_encoders]]
=== Configuring Pins for Controlling Encoders
==== Problem
You want to ((configure)) the pins so the PRU _inputs_ are accessable.

==== Solution
It depends on which Beagle you are running on.  If you are on the Blue, everything is already configured for you.
If you are on the Black or Pocket you'll need to run the following script.

.encoder_setup.sh
[source,linenums]
----
include::code/encoder_setup.sh[encoder_setup.sh]
----

==== Discussion
This works like the servo setup except some of the pins are configured as 
to the hardware eQEPs and other to the PRU inputs.

